version: '3.9'
services:
  stirling-pdf:
    container_name: Stirling-PDF
    image: frooodle/s-pdf
        
     test: curl -f http://localhost:8080/ || exit 1
    ports:
      - 3006:8080
    volumes:
      - /volume1/docker/stirling/data:/usr/share/tesseract-ocr/5/tessdata:rw # Required for extra OCR languages
      - /volume1/docker/stirling/config:/configs:rw
      - /volume1/docker/stirling/logs:/logs:rw
    environment:
     
     APP_LOCALE: es_ES
     APP_HOME_NAME: EDITOR PDF FED SERVICIOS
     APP_HOME_DESCRIPTION: Aplicación local para gestión de PDF
     APP_NAVBAR_NAME: Stirling PDF
     APP_ROOT_PATH: /
     ALLOW_GOOGLE_VISIBILITY: false


      
