version: '3.9'
services:
  stirling-pdf:
    image: frooodle/s-pdf
    container_name: s-pdf
    ports:
      - '3006:8080'
    volumes:
      - ./spdf/trainingData:/usr/share/tesseract-ocr/4.00/tessdata #Required for extra OCR languages
      - ./spdf/extraConfigs:/configs
    environment:
     
     APP_LOCALE: es_ES
     APP_HOME_NAME: EDITOR PDF FED SERVICIOS
     APP_HOME_DESCRIPTION: Aplicación local para gestión de PDF
     APP_NAVBAR_NAME: Stirling PDF
     APP_ROOT_PATH: /
     ALLOW_GOOGLE_VISIBILITY: false


      
